---
title: "Giuseppe Tinti Tomio's CV"
author: "Giuseppe Tinti Tomio"
date: "`r Sys.Date()`"
output:
    pagedown::html_resume:
        self_contained: true
        css:
            - "../css/CV.css"  # For some reason, css path is relative to .Rmd source instead of knit_root_dir
            - "resume"         # Built-in CSS file as described in pagedown::html_paged
---

Aside
==============================================================================

<i class="fas fa-phone"></i> Contact
------------------------------------------------------------------------------

<i class="fa fa-envelope"></i> [g.tinti.tomio@gmail.com](mailto:g.tinti.tomio@gmail.com)

<i class="fab fa-linkedin"></i> [linkedin.com/in/giuseppett](https://www.linkedin.com/in/giuseppett)

<i class="fa fa-github"></i> [github.com/GiuseppeTT](https://www.github.com/GiuseppeTT)

<i class="fas fa-language"></i> Language
------------------------------------------------------------------------------

**Portuguese:** native

**English:** proficient

<i class="fas fa-code"></i> Programming
------------------------------------------------------------------------------

<i class="fab fa-r-project"></i> `R`

<i class="fab fa-python"></i> `python`

<i class="fas fa-database"></i> `SQL`

<i class="fas fa-paragraph"></i> `LaTeX`

<i class="fas fa-code-branch"></i> `git`

<i class="fab fa-github"></i> `GitHub`

<i class="fab fa-docker"></i> `docker`

<i class="fab fa-linux"></i> `linux`

Disclaimer
------------------------------------------------------------------------------

Made with the R package [pagedown](https://github.com/rstudio/pagedown).

Up-to-date versions available for [web](https://giuseppett.github.io/CV/CV) and [PDF](https://github.com/GiuseppeTT/CV/raw/print/CV.pdf).

Source code on [GitHub](https://github.com/GiuseppeTT/CV).

Main
==============================================================================

Giuseppe Tinti Tomio {#title}
------------------------------------------------------------------------------

I am a MSc in statistics student at UBC, based in Vancouver. I have experience in both research and industry.

<i class="fas fa-graduation-cap"></i> Education
------------------------------------------------------------------------------

### University of British Columbia

MSc in Statistics

Vancouver - Canada

Present - 2021

Thesis: to be defined.

### National Institute for Pure and Applied Mathematics

Summer Course - Real Analysis

Rio de Janeiro - Brazil

2021

### University of Campinas

BSc in Statistics

Campinas - Brazil

2020 - 2016

<i class="fas fa-suitcase"></i> Professional Experience
------------------------------------------------------------------------------

### Goldman Sachs

Strategist Intern

S達o Paulo - Brazil

2020

- Worked on pricing automation of structured notes.
- Employed stochastic calculus and machine learning models.

### Institute of Mathematics and Statistics

Statistical Consultant

Campinas - Brazil

2020

- [(GitHub)](https://github.com/GiuseppeTT/me812) Provided statistical consulting to a linguistic professor with his study of the difference between the spoken-Portuguese of Angola and Mozambique.
- [(GitHub)](https://github.com/GiuseppeTT/me712) Provided statistical consulting to a biology Ph.D. candidate with his study of the impacts of genes RAG1 and RAG2 in the immune system of mice infected with the Oropouche virus.

<i class="fas fa-flask"></i> Research Experience
------------------------------------------------------------------------------

### Time Series, Econometrics and Finances Laboratory

Undergraduate Researcher

Campinas - Brazil

2021 - 2018

- Supervisor: Prof. Luiz Koodi Hotta
- Researched mathematical approaches to determine money and risk allocation when investing in multiple assets (e.g., stocks and bonds).
- Presented my work at Unicamp Undergraduate Research Congress.

### Organic Solids and New Materials Research Group

Undergraduate Researcher

Campinas - Brazil

2018 - 2016

- Supervisor: Prof. Douglas Soares Galv達o
- Designed graphene-based structures appropriate to build transistors with the aid of genetic algorithms.

<i class="fas fa-file-alt"></i> Publications
------------------------------------------------------------------------------

### Paper in progress

TODO

TODO

TODO

<i class="fas fa-award"></i> Awards
------------------------------------------------------------------------------

### S達o Paulo Research Foundation

Research Grant

Campinas - Brazil

2019

TODO (Description)

### S達o Paulo Research Foundation

Research Grant

Campinas - Brazil

2017

TODO (Description)

<i class="fas fa-book"></i> Reading Selection
------------------------------------------------------------------------------

### TODO

TODO

TODO

TODO
